name: MacOSBuild
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-12.2]
        qt_ver: [6.2.2]
        qt_arch: [clang_64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'true'
      - name: Build 3rdpart
        run: |
          pwd
          cd tools/
          sh make_3rdpart_unix_m1.sh
