name: MacOSBuild
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build 3rdpart
        run: |
          uname -a
          brew install yasm
          brew install nasm
          cd tools/
          ls
          sh make_3rdpart_unix_m1.sh
          
      - name: Build EyerLib
        run: |
          cd tools/
          ls
          sh make_eyer_lib_m1.sh
          
      - name: Check
        run: |
          cd Lib
          ls
